theme: jekyll-theme-cayman
title: Alyssa Rose's Portfolio
description: A collection of the projects that I've led and collaborated on. I am a 3rd year undergrad at Tufts University
in the Data Science Program in the School of Engineering
